### ISSUE TITLE
Drawings functionality not in demonstrator

### ISSUE THREAD

**Issue by PhilBarrett** [PulseTile/PulseTile#15] opened 2017-06-08 08:44 UTC
Drawings functionality does not appear in the left hand menu / not hooked up to the demonstrator

**Comment by dkryvosheya** [comment] 2017-06-13 14:29
Present in most recent archives already; App should be reinstalled onto demonstrator machine

**Comment by PhilBarrett** [comment] 2017-06-15 14:08
Thanks @dkryvosheya - Uploading an image isn't working currently though, could you take a look please 

![image](https://user-images.githubusercontent.com/12699244/27185194-7bc7263e-51dc-11e7-9f8b-553a8200fa36.png)

**Comment by dkryvosheya** [comment] 2017-06-15 15:11
@PhilBarrett  @tony-shannon I'm not aware if Rob already added proxying the image over URL - I'll chase him tomorrow about this feature.

**Comment by tony-shannon** [comment] 2017-06-15 15:13
thankyou
T

**Comment by dkryvosheya** [comment] 2017-06-23 13:27
Parked for now, should I close the issue, @tony-shannon?

**Comment by tony-shannon** [comment] 2017-06-23 14:09
Sorry just tested by import image locally (24KB) in size
Still not working, see picture, no response when clicked complete, see console error about being too large

![image](https://user-images.githubusercontent.com/939996/27485770-fa744e68-5825-11e7-9b4f-abf14fd3e49d.png)

**Comment by dkryvosheya** [comment] 2017-06-26 07:51
@tony-shannon My guesses are that middleware does not allow us to post the canvas data, I think that Rob can increase the threshold for canvas sizes in this case.

**Comment by dkryvosheya** [comment] 2017-06-26 10:14
Passed over to QEWD repository; https://github.com/RippleOSI/Ripple-Qewd/issues/42

**Comment by tony-shannon** [comment] 2017-06-26 10:37
thanks @dkryvosheya 
Again please keep this open until the related QEWD issue has been resolved and retested in the PulseTile UI
thanks
Tony

**Comment by tony-shannon** [comment] 2017-06-28 15:44
@dkryvosheya Can you please check the UI side of this again please as Rob has made some changes
see latest chrome error on testing
![image](https://user-images.githubusercontent.com/939996/27646608-fa098502-5c20-11e7-8970-88d6e22758ac.png)

**Comment by tony-shannon** [comment] 2017-06-28 16:39
Rob has confirmed that understanding 

> I can see that the drawing base64 is being saved against 9999999000 and being retrieved.  The problem is how the base64 data is being used in the UI to re-create the image

**Comment by dkryvosheya** [comment] 2017-06-30 17:10
Updated the library - not closing the issue at the moment, will play around it over the weekend to see if the solution worked out;

**Comment by tony-shannon** [comment] 2017-06-30 17:25
tested & still not quite working..
T

**Comment by dkryvosheya** [comment] 2017-07-03 11:20
Elder ones (since they were not saved properly) will not be able to display - since they're stored already broken. 
I've created a couple of new drawing records for Ivor Cox, and everything is OK.

**Comment by tony-shannon** [comment] 2017-07-03 12:19
thanks Dmitry
I'll aim to retest that/those & catchup with you tomorrow, Tuesday 4/7
thanks again
T

**Comment by tony-shannon** [comment] 2017-07-04 08:05
This seems to be working thanks

**Closed by tony-shannon** 2017-07-04 08:05 UTC
Labels: bug, SinglePatientView
